name: ECommerceSystem
services:
  grpc-dev:
    image: grpc-dev:v2
    container_name: grpc-dev
    restart: unless-stopped
    ports:
      - "10022:22"
    volumes:
      - ..:/app
      - clion_cache:/root/.cache/JetBrains  # 持久化 clion 后端环境
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - grpc-net

  # Envoy 网关服务
  envoy-gateway:
    image: envoyproxy/envoy:contrib-v1.34.9
    container_name: envoy-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../apiGateway/envoy.yaml:/etc/envoy/envoy.yaml
      - ../apiGateway/proto.pb:/etc/envoy/proto.pb
    networks:
      - grpc-net
    depends_on:
      - grpc-dev

  # Postgresql 持久化
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lxy
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - grpc-net

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - grpc-net

volumes:
  clion_cache:
  postgres-data:
  redis-data:

networks:
  grpc-net:
    driver: bridge